apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      nodeName: nodeserf1
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "while(1){print bpi(2000);}"]
      restartPolicy: Never
  backoffLimit: 4
