apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataread-deployment
  labels:
    app: data-reading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-reading
  template:
    metadata:
      name: dataread   
      labels:   
        app: data-reading  
    spec:
      nodeName: nodeserf2
      containers:   
      - image: lucaserf/reading_agent:cloudevents
        imagePullPolicy: Always
        name: dataread
        ports:   
        - containerPort: 3000
        volumeMounts:
          - name: pvlog
            mountPath: /var/log/pv/
      volumes:
      - name: pvlog
        persistentVolumeClaim:
         claimName: reader-log-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: reader-service
spec:
  selector:
    app: data-reading
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 3000
  type: ClusterIP

  