apiVersion: v1
kind: Service
metadata:
  name: reader-service
spec:
  clusterIP: None
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: data-reading
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: data-reading
  name: dataread-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-reading
  template:
    metadata:
      labels:
        app: data-reading
      name: dataread
    spec:
      containers:
      - image: lucaserf/reading_agent:latest
        imagePullPolicy: Always
        name: dataread
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /var/log/pv/
          name: pvlog
      nodeName: nodeserf2
      volumes:
      - name: pvlog
        persistentVolumeClaim:
          claimName: reader-log-pvc
