apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-data-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 15Gi
  volumeName: log-data-pv