apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gen-log-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi
  volumeName: gen-log-pv