apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
spec:
  selector:
    app: data-generation-example
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: NodePort


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datagen-deployment
  labels:
    app: data-generation-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-generation-example
  template:
    metadata:
      name: datagen   
      labels:   
        app: data-generation-example   
    spec:   
      containers:   
      - image: lucaserf/obs:server   
        name: datagen  
        ports:   
        - containerPort: 8080
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      volumes:
      - name: varlog
        emptyDir: {}