apiVersion: v1
kind: Service
metadata:
  name: server-gen-service
spec:
  selector:
    app: server-gen-example
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: NodePort


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-gen-deployment
  labels:
    app: server-gen-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-gen-example
  template:
    metadata:
      name: server-gen   
      labels:   
        app: server-gen-example   
    spec:   
      containers:   
      - image: lucaserf/obs:server   
        name: server-gen  
        ports:   
        - containerPort: 8080
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      - image: lucaserf/logging_agent:latest
        name: logging-agent
        volumeMounts:
         - name: pvlog
           mountPath: /var/log/pv
         - name: varlog
           mountPath: /var/log
      volumes:
      - name: varlog
        emptyDir: {}
      - name: pvlog
        persistentVolumeClaim:
         claimName: myapp-log-pvc