apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudevents-gen-deployment
  labels:
    app: cloudevents-gen-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudevents-gen-example
  template:
    metadata:
      name: cloudevents-gen   
      labels:   
        app: cloudevents-gen-example   
    spec:   
      containers:   
      - image: lucaserf/obs:sim_log
        imagePullPolicy: Always   
        name: sim-gen  
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: data
          mountPath: /var/data/
      - image: lucaserf/logging_agent:cloudevents
        name: logging-agent
        imagePullPolicy: Always
        volumeMounts:
         - name: pvlog
           mountPath: /var/log/pv
         - name: varlog
           mountPath: /var/log
      volumes:
      - name: varlog
        emptyDir: {}
      - name: pvlog
        persistentVolumeClaim:
         claimName: myapp-log-pvc
      - name: data
        persistentVolumeClaim:
         claimName: log-data-pvc