apiVersion: apps/v1
kind: Deployment
metadata:
  name: datagen-deployment
  labels:
    app: data-generation-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-generation-example
  template:
    metadata:
      name: datagen   
      labels:   
        app: data-generation-example   
    spec:   
      containers:   
      - image: lucaserf/obs:gen   
        name: datagen  
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      - image: lucaserf/logging_agent:latest
        name: logging-agent
        volumeMounts:
         - name: pvlog
           mountPath: /var/log/pv
         - name: varlog
           mountPath: /var/log
      volumes:
      - name: varlog
        emptyDir: {}
      - name: pvlog
        persistentVolumeClaim:
         claimName: myapp-log-pvc


