apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: periodic-log-generator
  name: periodic-log-generator-job
spec:
  backoffLimit: 0
  completions: 100
  parallelism: 19
  template:
    spec:
      containers:
      - image: lucaserf/obs:sim_log
        imagePullPolicy: Always
        name: sim-gen
        volumeMounts:
        - mountPath: /var/log/
          name: varlog
        - mountPath: /var/data/
          name: data
      - image: lucaserf/logging_agent:cloudevents
        imagePullPolicy: Always
        name: logging-agent
        volumeMounts:
        - mountPath: /var/log/pv/
          name: pvlog
        - mountPath: /var/log/
          name: varlog
      nodeName: nodeserf1
      restartPolicy: Never
      volumes:
      - emptyDir: {}
        name: varlog
      - name: pvlog
        persistentVolumeClaim:
          claimName: gen-log-pvc
      - name: data
        persistentVolumeClaim:
          claimName: log-data-pvc
