apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: periodic-log-generator
  name: periodic-log-generator-job
spec:
  backoffLimit: 0
  completions: 100
  parallelism: 1
  template:
    spec:
      nodeName: nodeserf1
      containers:
      - image: lucaserf/obs:sim_log
        env:
        - name: START_TIME
          value: "0"
        - name: WAIT_TIME
          value: "100"
        - name: GEN_PERIOD
          value: "0.15"
        imagePullPolicy: Always
        name: sim-gen
        volumeMounts:
        - mountPath: /var/log/
          name: varlog
        - mountPath: /var/data/
          name: data
      - image: lucaserf/logging_agent:cloudevents
        env:
        - name: OPERATION_MODE
          value: "logs"
        imagePullPolicy: Always
        name: logging-agent
        volumeMounts:
        - mountPath: /var/log/pv/
          name: pvlog
        - mountPath: /var/log/
          name: varlog
      restartPolicy: Never
      volumes:
      - emptyDir: {}
        name: varlog
      - name: pvlog
        persistentVolumeClaim:
          claimName: gen-log-pvc
      - name: data
        persistentVolumeClaim:
          claimName: log-data-pvc
