apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: periodic-log-generator
  name: periodic-log-generator-job
spec:
  backoffLimit: 0
  completions: 100
  parallelism: 2
  template:
    spec:
      containers:
      - env:
        - name: START_TIME
          value: '1707238053.5927112'
        - name: WAIT_TIME
          value: '120'
        - name: GEN_PERIOD
          value: '0.15'
        - name: BATCH_SIZE
          value: '1'
        image: lucaserf/obs:sim_log
        imagePullPolicy: Always
        name: sim-gen
        volumeMounts:
        - mountPath: /var/log/
          name: varlog
        - mountPath: /var/data/
          name: data
      - env:
        - name: OPERATION_MODE
          value: logs
        image: lucaserf/logging_agent:cloudevents
        imagePullPolicy: Always
        name: logging-agent
        volumeMounts:
        - mountPath: /var/log/pv/
          name: pvlog
        - mountPath: /var/log/
          name: varlog
      nodeName: nodeserf1
      restartPolicy: Never
      volumes:
      - emptyDir: {}
        name: varlog
      - name: pvlog
        persistentVolumeClaim:
          claimName: gen-log-pvc
      - name: data
        persistentVolumeClaim:
          claimName: log-data-pvc
