apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: periodic-log-generator
  name: periodic-log-generator-job
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    spec:
      nodeName: nodeserf3
      # topologySpreadConstraints:
      # - maxSkew: 1 
      #   topologyKey: node-role.kubernetes.io/worker
      #   whenUnsatisfiable: DoNotSchedule
      #   labelSelector: 
      #     matchLabels:
      #       app: periodic-log-generator
      containers:
      - image: lucaserf/obs:sim_log
        env:
        - name: START_TIME
          value: "0"
        - name: WAIT_TIME
          value: "100"
        - name: GEN_PERIOD
          value: "0.15"
        - name: BATCH_SIZE
          value: "1"
        - name: SEED
          value: "42"
        imagePullPolicy: Always
        name: sim-gen
        volumeMounts:
        - mountPath: /var/log/
          name: varlog
        - mountPath: /var/data/
          name: data
      - image: lucaserf/logging_agent:latest
        env:
        - name: OPERATION_MODE
          value: "logs"
        - name: AUTO_SELECTION
          value: "False"
        - name: LOGS_TO_SEND
          value: "inf"
        imagePullPolicy: Always
        name: logging-agent
        volumeMounts:
        - mountPath: /var/log/pv/
          name: pvlog
        - mountPath: /var/log/
          name: varlog
      restartPolicy: Never
      volumes:
      - emptyDir: {}
        name: varlog
      - name: pvlog
        persistentVolumeClaim:
          claimName: gen-log-pvc
      - name: data
        persistentVolumeClaim:
          claimName: log-data-pvc
