apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: periodic-log-generator
  name: periodic-log-generator-job
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - env:
        - name: START_TIME
          value: '1739296497.8985977'
        - name: WAIT_TIME
          value: '100'
        - name: GEN_PERIOD
          value: 0.03,0.03
        - name: BATCH_SIZE
          value: 1,False
        - name: SEED
          value: '42'
        - name: DATANAME
          value: BGL_created.log
        image: lucaserf/obs:sim_log
        imagePullPolicy: Always
        name: sim-gen
        volumeMounts:
        - mountPath: /var/log/
          name: varlog
        - mountPath: /var/data/
          name: data
      - env:
        - name: OPERATION_MODE
          value: anomaly
        - name: AUTO_SELECTION
          value: 'False'
        - name: LOGS_TO_SEND
          value: '8000'
        image: lucaserf/logging_agent:latest
        imagePullPolicy: Always
        name: logging-agent
        volumeMounts:
        - mountPath: /var/log/pv/
          name: pvlog
        - mountPath: /var/log/
          name: varlog
      nodeName: nodeserf3
      restartPolicy: Never
      volumes:
      - emptyDir: {}
        name: varlog
      - name: pvlog
        persistentVolumeClaim:
          claimName: gen-log-pvc
      - name: data
        persistentVolumeClaim:
          claimName: log-data-pvc
