apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{name}"
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: "{size}"
  volumeName: "{volume_name}"